pipeline:
  build:
    image: golang:1.8
    environment:
      - GOPATH=/drone
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.buildNumber=${DRONE_BUILD_NUMBER}" -o fluentd-metrics main.go
  publish:
    image: plugins/docker
    repo: registry.usw.co/cloud/fluentd-metrics
    tags: [ "${DRONE_COMMIT_SHA:0:8}", "latest" ]
